---
azs:
- name: us-central1-a
  cloud_properties:
    zone: us-central1-a

networks:
- name: bosh-subnet
  type: manual
  subnets:
  - dns:
    - 169.254.169.254
    - 8.8.8.8
    range: 10.0.1.0/24
    gateway: 10.0.1.1
    azs:
    - us-central1-a
    cloud_properties:
      network_name: ((env_name))-pcf-network
      subnetwork_name: ((env_name))-bosh-subnet
    reserved: []
    static: [10.0.1.2-10.0.1.50]

vm_types:
- name: micro
  cloud_properties:
    cpu: 1
    ram: 1024
    root_disk_size_gb: 11
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: micro.cpu
  cloud_properties:
    cpu: 2
    ram: 2048
    root_disk_size_gb: 11
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: small
  cloud_properties:
    cpu: 1
    ram: 2048
    root_disk_size_gb: 11
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: small.disk
  cloud_properties:
    cpu: 1
    ram: 2048
    root_disk_size_gb: 19
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: medium
  cloud_properties:
    cpu: 2
    ram: 4096
    root_disk_size_gb: 11
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: medium.mem
  cloud_properties:
    cpu: 1
    ram: 6144
    root_disk_size_gb: 11
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: medium.disk
  cloud_properties:
    cpu: 2
    ram: 4096
    root_disk_size_gb: 35
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: medium.cpu
  cloud_properties:
    cpu: 4
    ram: 4096
    root_disk_size_gb: 11
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: large
  cloud_properties:
    cpu: 2
    ram: 8192
    root_disk_size_gb: 19
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: large.mem
  cloud_properties:
    cpu: 2
    ram: 12288
    root_disk_size_gb: 19
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: large.disk
  cloud_properties:
    cpu: 2
    ram: 8192
    root_disk_size_gb: 67
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: large.cpu
  cloud_properties:
    cpu: 4
    ram: 4096
    root_disk_size_gb: 19
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: xlarge
  cloud_properties:
    cpu: 4
    ram: 16384
    root_disk_size_gb: 35
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: xlarge.mem
  cloud_properties:
    cpu: 4
    ram: 24576
    root_disk_size_gb: 35
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: xlarge.disk
  cloud_properties:
    cpu: 4
    ram: 16384
    root_disk_size_gb: 131
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: xlarge.cpu
  cloud_properties:
    cpu: 8
    ram: 8192
    root_disk_size_gb: 35
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: 2xlarge
  cloud_properties:
    cpu: 8
    ram: 32768
    root_disk_size_gb: 67
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: 2xlarge.mem
  cloud_properties:
    cpu: 8
    ram: 49152
    root_disk_size_gb: 67
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: 2xlarge.disk
  cloud_properties:
    cpu: 8
    ram: 32768
    root_disk_size_gb: 259
    root_disk_type: pd-standard
    tags:
    - pcf-vms
- name: 2xlarge.cpu
  cloud_properties:
    cpu: 16
    ram: 16384
    root_disk_size_gb: 67
    root_disk_type: pd-standard
    tags:
    - pcf-vms

disk_types:
- name: '1024'
  disk_size: 1024
  cloud_properties:
    type: pd-standard
- name: '2048'
  disk_size: 2048
  cloud_properties:
    type: pd-standard
- name: '5120'
  disk_size: 5120
  cloud_properties:
    type: pd-standard
- name: '10240'
  disk_size: 10240
  cloud_properties:
    type: pd-standard
- name: '20480'
  disk_size: 20480
  cloud_properties:
    type: pd-standard
- name: '30720'
  disk_size: 30720
  cloud_properties:
    type: pd-standard
- name: '51200'
  disk_size: 51200
  cloud_properties:
    type: pd-standard
- name: '76800'
  disk_size: 76800
  cloud_properties:
    type: pd-standard
- name: '102400'
  disk_size: 102400
  cloud_properties:
    type: pd-standard
- name: '153600'
  disk_size: 153600
  cloud_properties:
    type: pd-standard
- name: '204800'
  disk_size: 204800
  cloud_properties:
    type: pd-standard
- name: '307200'
  disk_size: 307200
  cloud_properties:
    type: pd-standard
- name: '512000'
  disk_size: 512000
  cloud_properties:
    type: pd-standard
- name: '768000'
  disk_size: 768000
  cloud_properties:
    type: pd-standard
- name: '1048576'
  disk_size: 1048576
  cloud_properties:
    type: pd-standard
- name: '2097152'
  disk_size: 2097152
  cloud_properties:
    type: pd-standard
- name: '5242880'
  disk_size: 5242880
  cloud_properties:
    type: pd-standard
- name: '10485760'
  disk_size: 10485760
  cloud_properties:
    type: pd-standard
- name: '16777216'
  disk_size: 16777216
  cloud_properties:
    type: pd-standard

compilation:
  workers: 4
  network: bosh-subnet
  az: us-central1-a
  reuse_compilation_vms: true
  vm_type: large.cpu
  vm_extensions:
  - public_ip

vm_extensions:
- name: public_ip
  cloud_properties:
    ephemeral_external_ip: true
    tags:
      - internal

variables:
- name: env_name
  type: string
